### ISSUE TITLE
global search only search in last visited crag

### ISSUE THREAD

**Issue by nicHoch** [theCrag/tca#65] opened 2021-03-16 09:50 UTC
reproduce: example https://thecrag.topoguru.com/info/12495061

- opening a crag from the map.
- do some browsing and going back to map 
- now open the global search
- now it is only possible to search within the last visited crag 
- it is not clear how to reset the search filter to global again

![image](https://user-images.githubusercontent.com/2226714/111289434-70e73c80-8645-11eb-985e-9ed3ad8b6a8a.png)

**Comment by bkucsera** [comment] 2021-03-17 11:14
You can switch to the global search with the "globe" icon on the right side of the search bar.
Do you have any suggestions, how to make it more clear for the users?

**Comment by nicHoch** [comment] 2021-03-17 11:22
ahh ok.
hmm not very self explaining - but i have also no better idea.
But if the user leaves an crag and is going back to the map - it would be helpful to automatically trigger that option.

**Comment by andrasbari** [comment] 2021-03-17 11:26
<-- 400 Bad Request https://www.thecrag.com/api/facet/areas/at/7546063/of-area-type/region/search/aus?perPage=100&page=1&minobject=1&pretty=0&key=abc123
The World's node id is 7546063. We have got HTTP 400 error code for response. I think it caused by the limitation of our api key.
@scd

**Comment by bkucsera** [comment] 2021-03-17 11:32
We try something more visible, probably an animation on the globe button.

**Comment by rouletout** [comment] 2021-03-17 17:30
wow, never tried this before but failed epically to find anything. Even clicking on the globe doesn't help me to find zillertal or kufstein. i simply don't get anything. How is this supposed to work?

**Comment by bkucsera** [comment] 2021-03-18 14:10
If you click on the globe icon to switch it to blue color, the search still doesnt work for you?
I attached a screenshot from my device.

![Screenshot_20210318-150319_Topo Guru.jpg](https://user-images.githubusercontent.com/78022975/111640019-12b08a00-87fc-11eb-8f71-67e3e84fab0a.jpg)

**Comment by nicHoch** [comment] 2021-03-21 19:16
i have seen the new animation on the "global" icon. But i do not think that this is solving the main issue here. 

The search is only available from the map page what i interpret as some kind of world level.

If i click right away on the search icon (what is do not interpret as a search icon should be a magnifier and not the "menu" icon)
from the map (word level) i really expect that i can search all areas - what it does - good.

But If i select a crag from the map and "enter" this crag. I have no chance to do a proper search besides the route search in the "routes" tab. if i want to search within this crag i have to go back to map (world level) and open the search there. Now it suddenly the app remembers my last crag and only searches there.
This is totally unexpected behavior.

I would suggest to make that search also available from within a crag page - from there the search should only search in the subtree. But the search available from the map should always search on country level (or maybe later on only on the map view box - i guess this is a bit more sophisticated and can wait fro a later release)

**Comment by rouletout** [comment] 2021-03-22 00:33
@bkucsera I think I understood how it works but I tried to search for "säli" and I only get 1 route and no areas, can you check that?

**Comment by killakalle** [comment] 2021-03-27 01:18
If it's of any valuable input:
- I can confirm that I did not find the Search functionality quickly (I eventually found it)
- I was initially confused why the search would not find anything
- eventually I figured out that clicking the world icon would show me results - I did not understand that this was the difference between global and local search.

Some UX feedback
To me the search is one of the most important functionalities in theCrag. I use it all the time (on the website) to go to different crags or to find a route. When I open the app at the moment, I don't see the search functionality. However, it seems that from anywhere in the app I can go to my profile. I hardly ever need to go into my profile and look up my user name. I'd be happy to do 2-3 clicks to see my profile details. However, the search is super essential. It should be accessible all the time from everywhere

**Comment by killakalle** [comment] 2021-03-27 02:24
PS:
Why don't you put the search here? I don't think I need to see the big Topo Guru / the Crag label all the time. I know that I am using the app, the space would be better used with functionality that I need
![image](https://user-images.githubusercontent.com/30682796/112706450-7f82ee80-8ea4-11eb-80bc-01ef75047ee4.png)

Take a look at Google Maps for example. It doesn't say "GOOGLE MAPS" anywhere. But the Search box is very prominent

**Comment by bkucsera** [comment] 2021-03-31 17:00
The "list" icon going to be changed on the World Map view to a "search" icon, in the upper right corner. 
We can do modifications later to improve Search, lets check the first version with this solution.

**Comment by bkucsera** [comment] 2021-04-13 07:23
Fixed (v151), please check and close if works properly.

**Comment by rouletout** [comment] 2021-04-13 19:11
Search is now by default global which is nice. I have 2 things that (still) confuse me:

1) Now when I click search in an area it obviously searches only in that area which makes sense. But how do i search globally from there? Right now I have to click "back" (arrive on the map), click back again (arrive on area page), click back again (arrive on the map with the area selected), click search on top right - now I can finally search globally - I think there should be a shorter way

2) Once I open global search, I see a list of results starting with "Livingston Island", North Pole, etc.... - shouldn't this be empty?

@bkucsera please check / comment

**Comment by nicHoch** [comment] 2021-04-13 19:22
the "local" search is not so user friendly at the moment.
the grade filter (slider) triggers a tab swipe. and does not filter the routes on the fly.
also open the keyboard and press the search icon does not update the route list according the grade filter.

furthermore i would propose that the "route tab" within the local search is pre-selected if there are routes. 
for filtering routes what might be the most common local search you have to switch to the "route-tab" first.
also it looks like that the route search is using an api call. but the on devise instant filtering while typing would be more offline friendly and faster. as the data is already available. you can trigger a api search if in the soft keyboard the looking glass  is pressed.

**Comment by nicHoch** [comment] 2021-04-13 21:57
> Once I open global search, I see a list of results starting with "Livingston Island", North Pole, etc.... - shouldn't this be empty?

maybe not empty but filled with last visited area / downloaded areas  favorites .... but not the global index

**Comment by bkucsera** [comment] 2021-04-14 15:54
> Search is now by default global which is nice. I have 2 things that (still) confuse me:
> 
> 1. Now when I click search in an area it obviously searches only in that area which makes sense. But how do i search globally from there? Right now I have to click "back" (arrive on the map), click back again (arrive on area page), click back again (arrive on the map with the area selected), click search on top right - now I can finally search globally - I think there should be a shorter way
> 2. Once I open global search, I see a list of results starting with "Livingston Island", North Pole, etc.... - shouldn't this be empty?
> 
> @bkucsera please check / comment

1. What if we make the Topo Guru logo clickable at the upper left corner? If the user clicks on it, we drop back to the main search page.
Or do you have other ideas?
In the next version the menu will be in the footer, as we checked during the last call. What if we solve this issue there, with double clicking on the Search icon is reseting the Search menu?

2. Here the default setting will be Countries, so it will always start with the country list, by alphabetical order.
I think its better to have the nodes here, so the users can start browsing, not only search for an item.

**Comment by bkucsera** [comment] 2021-04-14 15:57
> the "local" search is not so user friendly at the moment.
> the grade filter (slider) triggers a tab swipe. and does not filter the routes on the fly.
> also open the keyboard and press the search icon does not update the route list according the grade filter.
> 
> furthermore i would propose that the "route tab" within the local search is pre-selected if there are routes.
> for filtering routes what might be the most common local search you have to switch to the "route-tab" first.
> also it looks like that the route search is using an api call. but the on devise instant filtering while typing would be more offline friendly and faster. as the data is already available. you can trigger a api search if in the soft keyboard the looking glass is pressed.

Grade filter slider is a bug, we fix it. Thanks for it!
Route search: we already use offline search, if the selected node has been opened earlier, so we have the meta data on the device. This is why it can work in offline as well.
starting with route tab: we fix it in the 2nd release, good idea!

**Comment by rouletout** [comment] 2021-04-21 14:16
Solved in 153 - default view is countries. Closing.

**Closed as completed by rouletout** 2021-04-21 14:16 UTC
Labels: Fix for next release, Area: Search
