### ISSUE TITLE
Profile country defaults to UK

### ISSUE THREAD

**Issue by matozoid** [theCrag/tca#35] opened 2021-02-16 09:17 UTC
I logged in with my thecrag account and found out that the country field in my profile was set to... I forgot, I think UK. I live in the Netherlands though.

**Comment by bkucsera** [comment] 2021-02-25 16:07
We dont get Country and City info from thcrag API, so it should be empty in Topo Guru app when you register. UK is interesting, we will check it.

**Comment by rouletout** [comment] 2021-03-22 00:42
@matozoid can you check this again please as we can't reproduce

**Comment by matozoid** [comment] 2021-03-22 08:52
I can't do a clean new user registration because I already registered, so I can't help anymore :-(

**Comment by bkucsera** [comment] 2021-03-23 16:19
As we don't have the data from the api, the app sets the country by the language/territory info of the device. 
So if you use english setting, it will be UK, if you use dutch language on your phone, it will be Netherlands.
Not 100% solution, but i think this is good for the first version.

Other option is we leave the country empty for every theCrag user.

**Comment by rouletout** [comment] 2021-04-21 14:13
Closing as it is based on device settings of the user.

**Closed as completed by rouletout** 2021-04-21 14:13 UTC
Labels: Type: Bug, Area: Login & Registration, Fix for next release
